spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  hibernate:
    ddl-auto: update

  data:
    web:
      pageable:
        one-indexed-parameters: true

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

server:
  port: 8080

